version: '3'
services:
  python:
    image: ex21/python:1.0
    build: ./python
    container_name: 'ex21-python'
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes: 
      - ../python:/tmp/work
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519
